### ISSUE TITLE
Dead link to 'The Hidden Ingredient of Good Software Development'

### ISSUE THREAD

**Issue by Ivkaa** [LappleApple/awesome-leading-and-managing#100]
[Empathy - The Hidden Ingredient of Good Software Development (video)](http://www.ustream.tv/recorded/86154111)
Link is in file `./Abilities-Qualities-Values.md`
Not sure if 
- delete it 
- look for other place that hosts the resource

**Comment by davidlanouette** [comment]
Slide deck for this is on SlideShare:
https://www.slideshare.net/dbryant_uk/craftconf16-empathy-the-hidden-ingredient-of-good-software-development

Though not the same conference, it looks like he gave the same talk at JAX London 2016. 
 It's on YouTube at https://www.youtube.com/watch?v=XXM7sJEjB0U

Though it's looks like the slides are the same, I have not seen the original linked talk, so I cannot confirm if this is the same talk.  (maybe it doesn't matter, and this one is "close enough")

**Comment by davidlanouette** [comment]
Also, looks like this issue is already addressed in https://github.com/LappleApple/awesome-leading-and-managing/pull/109
