### ISSUE TITLE
Suggestion: Category for leadership forums

### ISSUE THREAD

**Issue by cjhuitt** [LappleApple/awesome-leading-and-managing#101]
I'd love to know of more places to discussion management and leadership issues with people and get feedback on them.

Ones I know about:

Web
- https://www.manager-tools.com/forums
- https://www.reddit.com/r/cscareerquestions/
- https://www.askamanager.org/

Slack:
- Rands-Leadership (http://randsinrepose.com/welcome-to-rands-leadership-slack/)
- Software Lead Weekly (http://softwareleadweekly.com; offered to email subscribers)

**Comment by LappleApple** [comment]
Thank you for the suggestion. Want to add these two a new page?
