### ISSUE TITLE
Broken link to "Brilliant Jerks Cost More Than They Are Worth"

### ISSUE THREAD

**Issue by fogfish** [LappleApple/awesome-leading-and-managing#111]
Section **Conflict Prevention and Conflict Resolution**

Brilliant Jerks Cost More Than They Are Worth - by Retrospective.co/Anonymous. Takeaway: "Brilliant jerks harm team morale and productivity. "They don’t have to worry about being nice, because they are the top dog, and people need their natural talent. They have no incentive to try to improve, because they can simply go somewhere else. If you look carefully, you’ll notice that they often bounce around from place to place. They know they can get away with it." You must apply a "no jerks" policy.

**Comment by fogfish** [comment]
I was not able to find this article anywhere else.  The domain retrospective.co is suspended atm.

**Comment by davidlanouette** [comment]
If it helps, the article is archived at https://web.archive.org/web/20170215230326/https://retrospective.co/brilliant-jerks-cost-more-than-they-are-worth/

**Comment by fogfish** [comment]
Nice! Thank you a lot! I've completely forgot about webarchive.
