### ISSUE TITLE
Leadership-Philosophies-and-Styles.md duplicated error

### ISSUE THREAD

**Issue by onestraw** [LappleApple/awesome-leading-and-managing#139]
- [How Do You Measure Leadership?](https://blog.ycombinator.com/how-do-you-measure-leadership/) - by Ali Rowghani. Takeaway: three traits of effective leaders, including "Clarity of Thought and Communication"; "Clarity of Thought and Communication," and "Personal Integrity and Commitment."

**Comment by onestraw** [comment]
- [How Do You Measure Leadership?](https://blog.ycombinator.com/how-do-you-measure-leadership/) - by Ali Rowghani. Takeaway: three traits of effective leaders, including "Clarity of Thought and Communication"; "Judgment About People" and "Personal Integrity and Commitment."

**Comment by LappleApple** [comment]
Thanks! Fixed.
