### ISSUE TITLE
Link 404 Not found

### ISSUE THREAD

**Issue by ahmetsonmez** [LappleApple/awesome-leading-and-managing#145]
https://github.com/LappleApple/awesome-leading-and-managing/blob/master/Building-Teams.md > The Five Dysfunctions of a Team: a Leadership Fable 

The link in this topic gives 404 not found error. fyi.

**Comment by darigovresearch** [comment]
@ahmetsonmez thanks for raising this as an issue!

The internet archive has a recent capture of it but not sure if this is the right one - https://web.archive.org/web/20171118123522/http://www.bip.org.bd:80/SharingFiles/11-The%20Five%20Dysfunctions%20of%20a%20Team.pdf

Can any maintainers of the repository advise if this is the right one?

**Comment by LappleApple** [comment]
Thanks, I changed it.

**Comment by darigovresearch** [comment]
Thanks @LappleApple for the fix!
