### ISSUE TITLE
to add

### ISSUE THREAD

**Issue by LappleApple** [LappleApple/awesome-leading-and-managing#18]

**Comment by fokusferit** [comment]
Also: http://firstround.com/review/our-6-must-reads-for-scaling-yourself-as-a-leader/

**Comment by Seanstoppable** [comment]
Note, the Daniel Levitin Ted Talk is essentially very briefly talking about pre-mortems (with a bunch of medical examples). This is probably already covered by "Why Airbnb Encourages Employees to Predict Its Own Downfall"
