### ISSUE TITLE
Add "Hiring and Firing" sub-page

### ISSUE THREAD

**Issue by LappleApple** [LappleApple/awesome-leading-and-managing#6]
Upload these links to create the page: https://docs.google.com/document/d/1hcPa4BHIOFJX94npY5Du2BzKnmuEvONLZ-Zw-fuMFso/edit#heading=h.v642s1e6gsgs

If you want to claim this and start working, let us know first. About five style guidelines to follow (easy).

**Comment by Seanstoppable** [comment]
I've started going through this one.

**Comment by LappleApple** [comment]
Thanks, @Seanstoppable!
