### ISSUE TITLE
Add "Motivation and “Retention” sub-page contents

### ISSUE THREAD

**Issue by LappleApple** [LappleApple/awesome-leading-and-managing#7]
Upload these links to create the page: https://docs.google.com/document/d/1EU8J3zL12oAQhlfdMdJS2Vols5srOANBo5ya73kHlug/edit

If you want to claim this and start working, let us know first. About five style guidelines to follow (easy).

**Comment by fokusferit** [comment]
To finish our efforts, I'd like to start with it.

**Comment by LappleApple** [comment]
@fokusferit cool!
