### ISSUE TITLE
Coinhive in one of the links

### ISSUE THREAD

**Issue by icnagy** [LappleApple/awesome-leading-and-managing#77]
Hi folks,

The following link contains coinhive:

http://silverwraith.com/blog/2017/10/the-senior-engineers-guide-to-helping-others-make-decisions/

![image](https://user-images.githubusercontent.com/556445/33492257-66002992-d6b4-11e7-9b74-87b9d8374466.png)

**Comment by LappleApple** [comment]
@icnagy noted and corrected — thanks!
