### ISSUE TITLE
commit break external references

### ISSUE THREAD

**Issue by walidshaari** [LappleApple/awesome-leading-and-managing#88]
the commit  ff386e894b0548f58  'Rename Hiring-and-Firing.md to Hiring-and-Interviewing.md' broke your external reference comments leading back to your GitHub as you have changed the name in GitHub, however, you will not be able to change other site references to it. I guess now you have a dilemma, as any new references will be broken if you revert.  maybe a symlink to the old name would help

**Comment by LappleApple** [comment]
Oh, OK. Thanks!
