### ISSUE TITLE
Add "Postmortems, Retrospectives, and Conflict Resolution" sub-page

### ISSUE THREAD

**Issue by LappleApple** [LappleApple/awesome-leading-and-managing#9]
Upload these links to create the page: https://docs.google.com/document/d/1MpmmN6vvhKGKD5H_vY21bGt3u2ahPxjiBbim9JnHIDg/edit#heading=h.bosc5gvc54ax

If you want to claim this and start working, let us know first. About five style guidelines to follow (easy).

**Comment by fokusferit** [comment]
Will start with that soon!

**Comment by LappleApple** [comment]
Wow, then we're "done" @fokusferit :)
